export const SET_USER = 'SET_USER';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN';

export const SET_LOADING = 'SET_LOADING';

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

export const FETCH_GENDER_START = 'FETCH_GENDER_START';
export const FETCH_GENDER_SUCCESS = 'FETCH_GENDER_SUCCESS';
export const FETCH_GENDER_FAILURE = 'FETCH_GENDER_FAILURE';

export const FETCH_ROLE_START = 'FETCH_ROLE_START';
export const FETCH_ROLE_SUCCESS = 'FETCH_ROLE_SUCCESS';
export const FETCH_ROLE_FAILURE = 'FETCH_ROLE_FAILURE';

export const FETCH_POSITION_START = 'FETCH_POSITION_START';
export const FETCH_POSITION_SUCCESS = 'FETCH_POSITION_SUCCESS';
export const FETCH_POSITION_FAILURE = 'FETCH_POSITION_FAILURE';

export const FETCH_TIME_START = 'FETCH_TIME_START';
export const FETCH_TIME_SUCCESS = 'FETCH_TIME_SUCCESS';
export const FETCH_TIME_FAILURE = 'FETCH_TIME_FAILURE';

export const FETCH_PRICE_START = 'FETCH_PRICE_START';
export const FETCH_PRICE_SUCCESS = 'FETCH_PRICE_SUCCESS';
export const FETCH_PRICE_FAILURE = 'FETCH_PRICE_FAILURE';

export const FETCH_PAYMENT_START = 'FETCH_PAYMENT_START';
export const FETCH_PAYMENT_SUCCESS = 'FETCH_PAYMENT_SUCCESS';
export const FETCH_PAYMENT_FAILURE = 'FETCH_PAYMENT_FAILURE';

export const FETCH_PROVINCE_START = 'FETCH_PROVINCE_START';
export const FETCH_PROVINCE_SUCCESS = 'FETCH_PROVINCE_SUCCESS';
export const FETCH_PROVINCE_FAILURE = 'FETCH_PROVINCE_FAILURE';
